site_name: Awesome Media
site_author: anon_fawkes
site_description: Awesome Media is a list of all the awesome software related to plex, emby and jellyfin.
site_url: https://awesome-media.net
repo_name: awesome-media
repo_url: https://github.com/johnfawkes/awesome-media

theme:
  name: material
  favicon: assets/favicon.ico
  custom_dir: overrides
  font:
    text: Open Sans
    code: Fira Code
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - toc.integrate
    - content.tooltips
  language: en
  icon:
    logo: material/video-vintage
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
hooks:
  - hooks/copyright.py
plugins:
  - macros: {}
  - tags:
      enabled: true
      tags: true
      tags_slugify_format: "tag:{slug}"
      tags_hierarchy: true
      tags_name_property: tags
      tags_name_variable: tags
      listings: true
      listings_directive: material/tags
      shadow: false
      shadow_on_serve: true
      shadow_tags_prefix: _
      export: true
      export_file: tags.json
      export_only: true
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - include-markdown
  - glightbox
  - material-plausible
  - render_swagger
  - social:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/social
      cards: true
      log: true
      cards_dir: assets/images/social
      cards_layout_dir: layouts
      debug: true
      debug_on_build: false
      debug_grid: true
      debug_grid_step: 32
      debug_color: yellow
  - tags:
      enabled: true
      tags_slugify_separator: "-"
  - open-in-new-tab

  # CI=true mkdocs build
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized:
            type: date
            fallback_to_build_date: false
            enable_creation_date: false
            enabled: true
        - git-committers:
          enabled: true
          cache_dir: .cache/plugins/git-commiters
          repository: johnfawkes/awesome-media
          branch: main
          token:
            !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
        - git-authors:
            enabled: true

  # INSIDERS=true mkdocs build
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize:
            enabled: true
            cache: true
            cache_dir: .cache/plugins/optimize
            optimize_png: true
            optimize_png_speed: 4
            optimize_png_strip: true
            optimize_jpg: true
            optimize_jpg_quality: 60
            optimize_jpg_progressive: true
            print_gain: true
            print_gain_summary: true
        - privacy:
          enabled: false
          cache: false
          cache_dir: .cache/plugins/privacy
          assets: true
          assets_fetch: true
          assets_fetch_dir: assets/external
          links: true
          links_noopener: true

extra:
  generator: true
  homepage: https://awesome-media.net/
  analytics:
    provider: plausible
    domain: awesome-media.net
    src: "https://analytics.servernation.xyz/js/script.js"
  social:
    - icon: fontawesome/brands/discord
      link: "https://discordapp.com/users/732333413008277504"
      name: "@anonfawkes"
    - icon: fontawesome/brands/github
      link: "https://github.com/johnfawkes"
      name: JohnFawkes on GitHub

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - neoteroi.cards
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
#extra_css:
#  - stylesheets/cards.css
#  - stylesheets/extra.css
#  - stylesheets/termynal.css
#  - stylesheets/custom.css

#extra_javascript:
#  - stylesheets/termynal.js
#  - stylesheets/custom.js
#  - stylesheets/branch.js
nav:
  - AWESOME MEDIA: index.md
  - THIRD PARTY SOFTWARE:
      - Bazarr: section/bazarr.md
      - Flixpatrol Top 10 on Trakt: section/flixpatrol-to-trakt.md
      - Kometa: section/kometa.md
      - Lidarr: section/lidarr.md
      - Maintainarr: section/maintainrr.md
      - Medialytics: section/medialytics.md
      - Notifiarr: section/notifiarr.md
      - Ombi: section/ombi.md
      - Overseerr: section/overseerr.md
      - PlexAniSync: section/plexanisync.md
      - PlexAutoLangauges: section/plexautolanguages.md
      - PlexTraktSync: section/plextraktsync.md
      - Prowlarr: section/prowlarr.md
      - Publier: section/publier.md
      - Radarr: section/radarr.md
      - Recyclarr: section/recyclarr.md
      - Sonarr: section/sonarr.md
      - Tautulli: section/tautulli.md
      - Title Card Maker: section/tcm.md
      - Tdarr: section/tdarr.md
      - Toolbarr: section/toolbarr.md
      - TRaSH: section/trash.md
      - Wizarr: section/wizarr.md
      - Wraperr: section/wrapperr.md
  - SCRIPTS:
      - Overview: section/scripts/scriptoverview.md
      - Kometa Scripts:
          - Romaji Renamer: section/scripts/kometa/romajirenamer.md
          - PATTRMM: section/scripts/kometa/pattrmm.md
      - Standalone Scripts:
          - Placeholder: ""
  # BULLMOOSE AND CHAZ
  - DOWNLOADING POSTERS:
      - Overview: section/posters/posteroverview.md
      - Kometa Poster Helpers:
          - Placeholder: ""
      - Standalone Poster Scripts:
          - Plex Poster Set Helper: section/posters/plex-poster-set-helper.md
          - Daps: section/posters/daps.md
### qBitManager  Upgradinatorr   reTraktArr   JBOPS
