site_name: Awesome Media
site_author: anon_fawkes
site_description: Awesome Media is a list of all the awesome software related to plex, emby and jellyfin.
site_url: https://awesome-media.net
repo_name: awesome-media
repo_url: https://github.com/johnfawkes/awesome-media
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    logo: material/video-vintage
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
# Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
# Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
# Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - privacy:
      enabled: false
      cache: false
      cache_dir: .cache/plugins/privacy
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
      links: true
      links_noopener: true
  - search
  - material-plausible
  - social:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/social
      cards: true
      log: true
      cards_dir: assets/images/social
      cards_layout_dir: layouts
      debug: true
      debug_on_build: false
      debug_grid: true
      debug_grid_step: 32
      debug_color: yellow
  - tags:
      enabled: true
      tags_slugify_separator: "-"
  - open-in-new-tab
extra:
  analytics:
    provider: plausible
    domain: awesome-media.net
    src: "https://analytics.servernation.xyz/js/script.js"
  social:
    - icon: fontawesome/brands/discord
      link: "https://discordapp.com/users/732333413008277504"
      name: "@anonfawkes"
    - icon: fontawesome/brands/github
      link: "https://github.com/johnfawkes"
      name: JohnFawkes on GitHub
copyright: >
  Copyright &copy; 2023 anon_fawkes
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
#  - toc:
#      permalink: true
nav:
#  - AWESOME MEDIA:
#    - index.md
  - THIRD PARTY SOFTWARE:
    - Bazarr: section/bazarr.md
    - Lidarr: section/lidarr.md
    - Maintainarr: section/maintainrr.md
    - Medialytics: section/medialytics.md
    - Notifiarr: section/notifiarr.md
    - Ombi: section/ombi.md
    - Overseerr: section/overseerr.md
    - Plex Meta Manager: section/pmm.md
    - Prowlarr: section/prowlarr.md
    - Publier: section/publier.md
    - Radarr: section/radarr.md
    - Sonarr: section/sonarr.md
    - Tautulli: section/tautulli.md
    - Title Card Maker: section/tcm.md
    - Tdarr: section/tdarr.md
    - Toolbarr: section/toolbarr.md
    - Wizarr: section/wizarr.md
    - Wraperr: section/wrapperr.md
  - SCRIPTS:
    - Overview: section/scriptoverview.md
  - DOWNLOADING POSTERS:
    - Overview: section/posteroverview.md