name: Build GitHub Pages

env:
  PYTHON_VERSION: "3.9"
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GH_TOKEN }}
  CI: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy_mkdocs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6
        
      - name: Checkout
        uses: actions/checkout@v7

      - name: Zensical Build
        uses: actions/setup-python@v7
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - run: zensical build --clean

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
