name: Tag New Version

on:
  push:
    branches:
      - main
      - production
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 2

      - uses: Kometa-Team/tag-new-version@master
        with:
          version-command: |
            cat VERSION
